### ISSUE TITLE
R8 full mode

### ISSUE THREAD

**Issue by nikanorov** [LiveTex/sdk-android#34]
В AGP 8.0+ [R8 full mode](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode) включен [по умолчанию](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes). 

R8 почему-то вырезает классы из ru.livetex.sdk.entity и Gson не может сериализовать ответ от сервера. Хотя я вижу, что у вас в proguard-rules есть правило для них, но видимо надо не только fields в исключение добавить теперь. 

Добавил в наш proguard более строгий -keep class ru.livetex.sdk.entity.** { *; }. Проблема исчезла.

Возможно что-то еще надо обновить, просто основные изменения для Gson мы уже затаскивали до этого (там в R8 FAQ есть примеры).

Пример ошибки: 
`E  Error when parsing message
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
                                                                                                    	at ru.livetex.sdk.logic.EntityMapper$LivetexTypeModelDeserializer.a(SourceFile:328)
                                                                                                    	at ru.livetex.sdk.logic.EntityMapper$LivetexTypeModelDeserializer.deserialize(SourceFile:1)
                                                                                                    	at com.google.gson.internal.bind.TreeTypeAdapter.read(SourceFile:36)
                                                                                                    	at com.google.gson.Gson.fromJson(SourceFile:17)
                                                                                                    	at com.google.gson.Gson.fromJson(SourceFile:10)
                                                                                                    	at com.google.gson.Gson.fromJson(SourceFile:4)
                                                                                                    	at com.google.gson.Gson.fromJson(SourceFile:1)
                                                                                                    	at ru.livetex.sdk.logic.EntityMapper.a(SourceFile:5)
                                                                                                    	at ru.livetex.sdk.logic.LiveTexMessagesHandler.o(SourceFile:31)
                                                                                                    	at ru.livetex.sdk.network.websocket.LiveTexWebsocketListener.onMessage(SourceFile:1)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.onReadMessage(SourceFile:1)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(SourceFile:61)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.processNextFrame(SourceFile:12)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.loopReader(SourceFile:11)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(SourceFile:122)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:41)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

`

**Comment by maxxx** [comment]
спасибо, на днях обновлю проект под последнюю студию и заодно это посмотрю

**Comment by maxxx** [comment]
должно быть исправлено в 1.3
